### ISSUE TITLE
[Install issue] No matching package found: ailove-dev/vk-php-sdk

### ISSUE THREAD

**Issue by akmetainfo** [MadFaill/vkApi#1]
Проблема при установке. Конфиг composer'а пуст, только "php":">=5.3.0"

Когда запускаю `composer require mad-tools/vk-api dev-master` ругается, что не может установить зависимости - не находит ailove-dev/vk-php-sdk - видимо, это что-то очень похожее на ailove-dev/vkPhpSdk но формально не то:

Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mad-tools/vk-api dev-master -> satisfiable by mad-tools/vk-api[dev-master].
    - mad-tools/vk-api dev-master requires ailove-dev/vk-php-sdk dev-master -> no matching package found

Хотя если ставить сначала `composer require ailove-dev/vk-php-sdk dev-master` то потом и vkApi ставится.

**Comment by MadFaill** [comment]
Благодарю за репорт, уже год как сюда не смотрел =)

**Comment by akmetainfo** [comment]
Спасибо за оперативность.
