### ISSUE TITLE
AuthFailed 'Wrong client id or scope'

### ISSUE THREAD

**Issue by akmetainfo** [MadFaill/vkApi#2]
При попытке авторизации [падает с исключением 'Wrong client id or scope'](https://github.com/MadFaill/vkApi/blob/master/src/VkApi/Auth.php#L124), проблема вот в чём.

При определении всех трёх параметров $origin, $ip_h и $to нужно ставить кавычки, иначе dom-парсер ничего не найдёт.
Т.е. было:
`php     $ip_h = $dom->get('input[name=ip_h]')->toArray();`
Надо:
`php     $ip_h = $dom->get('input[name="ip_h"]')->toArray();`
и так для всех трёх переменных.

**Comment by MadFaill** [comment]
Странно. Раньше весьма ре плохо работало ;)
Исправил, спасибо за репорт!

**Comment by akmetainfo** [comment]
Ниже вероятно ещё будет form[method="post"] -- но пока в эту ветку не попадал ))

**Comment by akmetainfo** [comment]
NB: Посмотреть [olamedia/nokogiri](https://github.com/olamedia/nokogiri) -- возможно, нужно поправить в их исходниках, чтобы кавычки отбрасывались.
