### ISSUE TITLE
Required $lg_h

### ISSUE THREAD

**Issue by akmetainfo** [MadFaill/vkApi#3]
И последнее, после чего у меня библиотека наконец-то заработала:

Нужно добавить

`php         $lg_h = $dom->get('input[name="lg_h"]')->toArray();`
и прокинуть переменную в вызове
`php         $auth_response = $this->auth_post_request($ip_h[0]['value'], $lg_h[0]['value'], $to[0]['value'], $origin[0]['value']);`
и определении функции
`php private function auth_post_request($ip_h, $lg_h, $to, $_origin)`
и проверять наличие в html:
`php if (!$ip_h || !$to || !$origin || $lg_hlg_h) {`

Видимо за год произошло обновление алгоритмов вконтакта в части авторизации.

Если непонятно или некогда разбираться -- могу оформить пулл риквест из своего форка.

**Comment by MadFaill** [comment]
В очередной раз благодарю за помощь. Да, по видимому за год что-то изменилось.

Можно и пулл реквест, однако я всеравно буду разбираться ;)

**Comment by akmetainfo** [comment]
@MadFaill оформил, проверяйте.

**Comment by akmetainfo** [comment]
Прекрасно. Обновил origin до upstream, забрал обновления из композера, тестовый пример на котором я проверял не поломался. Всё теперь будет работать до следующего обновления алгоритма vk.

**Comment by MadFaill** [comment]
Супер!
Благодарю за репорты и пулл-ы :)

Честно говоря, не думал что кому-либо пригодится ;)

**Comment by akmetainfo** [comment]
Самая популярный репозиторий по vk api для php - это по-прежнему https://github.com/vladkens/VK - и я им постоянно пользовался до тех пор, пока мне не понадобился метод, который только для standalone-приложений. 

Завёл тикет в ТП вконтакта, мол метод-то совершенно простой, не для спама, давайте не будем требовать для него права такие. Да, это давняя проблема и не факт, что ещё одно обращение что-то поменяет.

А пока искал костыль. Костылей (имитация браузера) нашлось много, пересмотрел все репозитории, но именно в этом мне понравился стиль и подход. Поэтому его и пошёл ставить.

И, честно говоря, очень не хотелось на ночь глядя отпиливать zend из https://github.com/superkozel/vk-repost ;)

На самом деле, посмотрите, у вашего решения много общего с vladkens/VK - и я подумывал над тем, чтобы только класс получения токена забрать.

**Comment by MadFaill** [comment]
По большому счету я создавал библиотеку именно из-за получения токена без дополнительных усилий. Враппер делал исключительно для себя, хотя на самом деле он тут нужен только для того чтобы автоматически пробрасывать токен из auth объекта. 

По началу думал убрать враппер, да лень стало... Потом и вовсе забыл...
