### ISSUE TITLE
[Install issue] No matching package found: olamedia/nokogiri

### ISSUE THREAD

**Issue by akmetainfo** [MadFaill/vkApi#6]
Аналогичная проблема как в  #1 - но теперь с dom-парсером.

Впечатление такое, что конфиг composer.json как-то некорректно оформлен, что не может самостоятельно разрешить зависимости.

Причём опять - можно поставить через composer require сначала olamedia/nokogiri и потом без проблем поставится поверх и MadFaill/vkApi.

Предлагаю при случае подкорректировать, пока же -- 'known issue'.

**Comment by MadFaill** [comment]
Да нет. Конфиг исправен. Переустановил 3 раза подряд. Все ок.

**Comment by akmetainfo** [comment]
Хорошо, давайте тогда закроем, раз не воспроизводится.

**Comment by akmetainfo** [comment]
NB: Возможно, нужно указать "minimum-stability": "dev"
http://kotoblog.pp.ua/php/composer-no-matching-package-found.html
Вообще, проблема много у кого встречается, если гуглить фразе No matching package found.
Надо только понять, какой у меня случай попался и почему не воспроизводится.

**Comment by MadFaill** [comment]
По всей видимости, имеет смысл просто убрать данный пункт из конфигурации composer.json.
