### ISSUE TITLE
Proposal: Exception 'Unknown result format' -> Throw error code & error_msg

### ISSUE THREAD

**Issue by akmetainfo** [MadFaill/vkApi#9]
Частенько получаю [эксепшн "неизвестный формат ответа"](https://github.com/MadFaill/vkApi/blob/master/src/VkApi/Api.php#L84).

И очень хочется посмотреть коды ошибок, которые прилетают.

Вот первый попавшийся пример из недавнего:

```
array(1) {
  ["error"]=>
  array(3) {
    ["error_code"]=>
    int(15)
    ["error_msg"]=>
    string(44) "Access denied: no access to call this method"
    ["request_params"]=>
```

Предлагаю допилить более тщательно отлавливание ошибок, сейчас дебажить крайне неудобно.

PS Николай, а вы вообще насколько заинтересованы этот проект поддерживать? Вижу, что пока риквесты принимаются положительно, вы скажите, если вам этот проект в паблике не особо интересен или у вас другие планы на его дальнейшее развитие -- я тогда в своём форке допилю то, что конкретно мне нужно под себя и не буду надоедать.

**Comment by MadFaill** [comment]
Андрей, конечно заинтересован!
Изначально в принципе рассматривал только как авторизацию на программном уровне. Поэтому особо не зацикливался. Более того использовал стороннюю библиотеку. Сейчас думаю-таки вернуть обратно к сторонним. Немного поресерчу и запилю просто небольшую фабрику, для возможности использовать инструмент по-вкусу.

**Comment by akmetainfo** [comment]
Пишите в почту, я вам как-то писал на @gmail поэтому адрес должен у вас остаться. Я тоже заинтересован как раз в модуле авторизации для standalone -- рабочем, постоянно поддерживаемом.

В принципе, если в проекте останется и опрос сервера, то у меня наверное ещё полторы фичи на дальнейшее развитие проекта потихоньку додумываются.

**Comment by akmetainfo** [comment]
Что любопытно: на один и тот же error_code у вк могут отправляться разные диагностические сообщения!

В первом посте я приводил пример ошибки error_code = 15 для метода groups.invite (пропало право groups для токена), а вот ещё пример неудачного вызова groups.invite - тоже получил error_code = 15, но уже другую текстовку:

```
array(1) {
  ["error"]=>
  array(4) {
    ["error_code"]=>
    int(15)
    ["error_msg"]=>
    string(27) "Access denied: already sent"
    ["error_text"]=>
    string(51) "Приглашение уже высылалось."
    ["request_params"]=>
```

В общем, очень хочется правильно получать от вк коды ошибок, чтобы можно было перехватывать и обрабатывать.

Посмотрел [в самом популярном репозитории](https://github.com/vladkens/VK) - там также этого нет. Надо пилить самому.

**Comment by akmetainfo** [comment]
Вот такой небольшой фикс предлагаю сделать.

**Comment by akmetainfo** [comment]
Кстати, иногда прилетает $result = null и эту ситуацию тоже можно индивидуально обработать.

**Comment by MadFaill** [comment]
Вмержил пул реквест, благодарю ;)
